### ISSUE TITLE
Support for custom dataset training

### ISSUE THREAD

**Issue by seyeong-han** [gligen/GLIGEN#38]
Thanks for your great effort and the results you have provided.

I wonder if you have any plans to provide a guideline on how to create custom dataset TSV files.
I am interested in reproducing your COCO dataset training results, but I am facing difficulties due to a lack of resources for creating TSV datasets.

I attempted to recreate the 'image_embedding_after' and 'image_embedding_before' data from the raw 'image' data in the flickr30k's TSV dataset, but unfortunately, I was unsuccessful in doing so.

For instance, I tried to using the data you provided in the HuggingFace dataset's flickr_tsv, which can be found [here](https://huggingface.co/datasets/gligen/flickr_tsv/viewer/gligen--flickr_tsv/train).

```
from ldm.modules.encoders.modules import FrozenClipImageEmbedder

# First solution
image = Image.open(image_path)
image = transforms.ToTensor()(image).unsqueeze(0).cuda()
clip_image_embedder = FrozenClipImageEmbedder("ViT-L/14", device="cuda", jit=False, antialias=False)
image_processed = clip_image_embedder.preprocess(image)
outputs = clip_image_embedder(image_processed)

# Second Solution
model = CLIPVisionModel.from_pretrained("openai/clip-vit-large-patch14")
processor = AutoProcessor.from_pretrained("openai/clip-vit-large-patch14")
inputs = processor(images=image, return_tensors="pt", padding=True, max_length=77, truncation=True)
outputs = model(**inputs)
```

The outputs I obtained are different from the "image_embedding_before" and "image_embedding_after" in the flickr_tsv dataset.
If you are unable to provide a solution directly at the moment, I would greatly appreciate any advice or guidance you can offer to help me resolve this issue.

**Comment by Yuheng-Li** [comment]
Hi, thanks for interesting our work. I have uploaded three scripts that we used for getting TSV in DATA folder. 

First run process_grounding.py to get all CLIP features (text and image) (before and after linear projection layer). Each embedding (for one bounding box) will be saved as a single file. The provided code is used for our data (GoldG, SBU, CC3M and O365). You may need to write you own __init__ and __getitem__ functions to fit your own current data format. 

Then, please run mydata_to_tsv.py to create a tsv file.

**Comment by seyeong-han** [comment]
Thanks for your sharing!!
I want to reproduce COCO2017D experiment from your paper.

If you don't have enough resources to provide TSV generation for the COCO detection dataset, I would like to contribute codes in your `process_grounding.py`.
Do you mind if I do that?

**Comment by seyeong-han** [comment]
Oh, I didn't know that O365 annotation json format is the same with COCO format.
I successfully convert the COCO annotation data with your `process_grounding.py`.

Thanks a lot!

**Comment by deschanel11** [comment]
Hi, can I ask where is the process_grounding.py file? Cause now I cannot find it
Or is it mydata_to_tsv.py??

**Comment by joonjeon** [comment]
Hi!

I attempted to reproduce your training step as follows:

```
python DATA/process_grounding.py --is_o365 True --json_path /home/joonjeon/data/COCO/training/stuff_train2017.json --image_root /home/joonjeon/data/COCO/training/images/
python DATA/mydata_to_tsv.py --which_dataset detection
python main.py --name=COCO --yaml_file=configs/coco2017D.yaml --official_ckpt_name=sd-v1-5-pruned.ckpt
```

But the error message says:
```
Traceback (most recent call last):
  File "/home/joonjeon/SDPipeline/GLIGEN/main.py", line 76, in <module>
    trainer.start_training()
  File "/home/joonjeon/SDPipeline/GLIGEN/trainer.py", line 388, in start_training
    loss = self.run_one_step(batch)
  File "/home/joonjeon/SDPipeline/GLIGEN/trainer.py", line 367, in run_one_step
    model_output = self.model(input)
  File "/home/joonjeon/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/joonjeon/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/joonjeon/SDPipeline/GLIGEN/ldm/modules/diffusionmodules/openaimodel.py", line 433, in forward
    objs = self.position_net( **grounding_input )  
  File "/home/joonjeon/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/joonjeon/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'boxes'
```

What should I do?

**Comment by joonjeon** [comment]
Hi? Could you share the proper config file for COCO2017D?

I tried to modify the configuration file for training on COCO2017K dataset to do so, but as the result of training, the bounding boxes won't match with the desired objects.

**Comment by joonjeon** [comment]
The same issue occurs with flickr.

I followed the exact steps as mentioned above, but even after training the bounding boxes won't match with the desired objects.

Please help me..

**Comment by joonjeon** [comment]
When I attempt to merge TSVs, the following error occurs:

```
ValueError: invalid literal for int() with base 10: '113880\t{"data_id": 113880, "image": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQgJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyM
```
