### ISSUE TITLE
Is it possible to train GLIGEN with a single GPU?

### ISSUE THREAD

**Issue by YJ-142150** [gligen/GLIGEN#48]
Thanks for your great work!
Is it possible to train GLIGEN with 3090TI?

**Comment by crj1998** [comment]
yes, with fp16 it vram usage is smaller than 24GB
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   49C    P0    96W / 250W |  16052MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by YJ-142150** [comment]
Thank you for answering the question!!

**Comment by Sjey-Lyn** [comment]
How long the training takes with 3090TI?

**Comment by yejinxueshi** [comment]
> 是的，对于 fp16，vram 使用量小于 24GB
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA A100-PCI...  Off  | 00000000:8B:00.0 Off |                    0 |
> | N/A   49C    P0    96W / 250W |  16052MiB / 40536MiB |    100%      Default |
> |                               |                      |             Disabled |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> +-----------------------------------------------------------------------------+
> ```
Where should I change the accuracy to fp16
