### ISSUE TITLE
Question for gligen_inference.py run(meta, config, starting_noise=None)

### ISSUE THREAD

**Issue by csw0109** [gligen/GLIGEN#58]
Great work! I wonder if there is a typo in gligen_inference.py run(meta, config, starting_noise=None), or can someone explain to me how this works? To me, it seems like it should be run(meta, args, starting_noise=None).
![image](https://github.com/gligen/GLIGEN/assets/89511003/a3c42568-8e68-4943-98b7-720b4a906a70)

**Comment by rohithpv** [comment]
I think it's a typo too.
