### ISSUE TITLE
incompatible packages

### ISSUE THREAD

**Issue by DinDjarin666** [gligen/GLIGEN#62]
Your work really impresses me a lot. However, when I tried to reproduce your work, something unexpected happened. Details as below:
when I tried to try out the demo by running command "conda env create -f environment.yaml", it failed. I got messages like this "Unsatisfiable Error: The following specifications were found to be incompatible with each other", it seems that there are some conflicts between the packages specified in the yaml file. I'm totally confused. Thanks for any help!

**Comment by CREED404** [comment]
I've identified the issue and made the necessary adjustments to resolve the conflicts in the environment.yml file. I've submitted a [pull request](https://github.com/gligen/GLIGEN/pull/66).
Feel free to give the pull request a look. If it's merged, awesome! You can simply pull the changes into your local environment. If not, you could clone [my forked repository](https://github.com/CREED404/GLIGEN/tree/fix_xformers_conflict_issue) and use the updated environment.yaml from there.

**Comment by DinDjarin666** [comment]
That really helps me a lot!  Thanks!

**Comment by CREED404** [comment]
You're welcome! I'm glad I could help
