### ISSUE TITLE
Using the "Image grounded generation"

### ISSUE THREAD

**Issue by GalDude33** [gligen/GLIGEN#9]
Hey, 
How can I use your code for "Image grounded generation" as described in the paper? How should I provide the grounding image?
Such as you show in Figure 9 in the paper? 
![image](https://user-images.githubusercontent.com/18334824/223205918-b2769116-02d6-4a5f-b0a0-b8af4ae65f3d.png)

Can you please share some instructions? 
Thanks!

**Comment by Kendrick-Stein** [comment]
Hello, so sorry to bother you. But I was wondering if you get any progress on this issue? because I was also trying to test out the image grounded generation and had absolutely no clue what to do? It would be highly appreciated if you could help me. thanks!
